package review

import (
	"context"
	"fmt"
	"strings"

	"github.com/nicolaeser/codereview/internal/gitlab"
)

const maxAskReplyChars = 8000

func (s *Service) replyAskIfNeeded(ctx context.Context, job Job, discussion gitlab.Discussion, extra string, notices []string) []string {
	if discussionHasAskReply(discussion) {
		return notices
	}
	askJob := job
	askJob.Ask = true
	askJob.ExtraFocus = extra
	askJob.DiscussionID = discussion.ID
	if err := s.answerMention(ctx, askJob); err != nil {
		s.logger.Warn("failed to answer @mention question", "request_id", job.RequestID, "discussion_id", discussion.ID, "error", err)
		return append(notices, "Could not answer an @mention question.")
	}
	return notices
}

func discussionHasAskReply(discussion gitlab.Discussion) bool {
	for _, note := range discussion.Notes {
		if ownedAskNote(note.Body) {
			return true
		}
	}
	return false
}

func (s *Service) answerMention(ctx context.Context, job Job) error {
	if strings.TrimSpace(job.ExtraFocus) == "" {
		return s.postAskBody(ctx, job, askUsageMarkdown(s.cfg.Review.Mention))
	}
	if s.cfg.Target.DryRun {
		s.logger.Info("dry-run: would answer @mention question", "request_id", job.RequestID, "project_id", job.ProjectID, "mr_iid", job.MergeRequest)
		return nil
	}
	mr, err := s.gitlab.GetMergeRequest(ctx, job.ProjectID, job.MergeRequest)
	if err != nil {
		return err
	}
	if mr.State != "opened" && mr.State != "locked" {
		return s.postAskBody(ctx, job, FormatAskReply("The merge request is not open, so this question was not answered against a live diff."))
	}
	headSHA := mr.SHA
	if headSHA == "" {
		headSHA = mr.DiffRefs.HeadSHA
	}
	mr.SHA = headSHA
	if err := s.applyReviewedRepoPolicy(ctx, mr); err != nil {
		return err
	}
	if reason := s.skipReason(mr); reason != "" {
		if strings.HasPrefix(reason, "disabled by") && s.cfg.Review.SkipAck && !s.cfg.Target.DryRun {
			if err := s.ackDisabledReview(ctx, job, mr, reason); err != nil {
				s.logger.Warn("could not post disabled-review note", "request_id", job.RequestID, "error", err)
			}
		}
		s.logger.Info("skipping @mention question; merge request is not reviewable", "request_id", job.RequestID, "reason", reason)
		return nil
	}
	maxFiles := s.cfg.Review.MaxDiffFiles
	if maxFiles <= 0 || maxFiles > 40 {
		maxFiles = 40
	}
	maxChars := s.cfg.Review.MaxDiffChars
	if maxChars <= 0 || maxChars > 80000 {
		maxChars = 80000
	}
	rawDiffs, err := s.gitlab.ListMergeRequestDiffs(ctx, job.ProjectID, job.MergeRequest, maxFiles*2)
	if err != nil {
		return err
	}
	prepared, _ := PrepareDiffs(rawDiffs, s.cfg.Review.IgnorePaths, maxFiles, maxChars)
	budget := s.cfg.AI.MaxInputChars
	if budget <= 0 || budget > 40000 {
		budget = 40000
	}
	raw, err := s.ai.Complete(ctx, BuildAskRequest(job.ExtraFocus, mr, prepared, budget))
	if err != nil {
		_ = s.postAskBody(ctx, job, FormatAskReply("CodeReview could not answer this question. Check the job logs for the provider error."))
		return err
	}
	return s.postAskBody(ctx, job, FormatAskReply(raw))
}

func (s *Service) postAskBody(ctx context.Context, job Job, body string) error {
	if s.cfg.Target.DryRun {
		s.logger.Info("dry-run: would post @mention answer", "request_id", job.RequestID)
		return nil
	}
	if job.DiscussionID != "" {
		_, err := s.gitlab.ReplyToDiscussion(ctx, job.ProjectID, job.MergeRequest, job.DiscussionID, body)
		return err
	}
	_, err := s.gitlab.CreateNote(ctx, job.ProjectID, job.MergeRequest, body)
	return err
}

func FormatAskReply(raw string) string {
	body := strings.TrimSpace(sanitizeModelText(raw))
	if body == "" {
		body = "The model returned an empty answer."
	}
	body = truncate(body, maxAskReplyChars)
	var builder strings.Builder
	builder.WriteString("## CodeReview\n\n")
	builder.WriteString(body)
	builder.WriteString("\n\n<sub>Generated by CodeReview. This is an AI answer to an @mention, not a full review. Verify before acting on it.</sub>\n")
	builder.WriteString(askMarker)
	return builder.String()
}

func askUsageMarkdown(mention string) string {
	mention = strings.TrimPrefix(strings.TrimSpace(mention), "@")
	if mention == "" {
		mention = "codereview"
	}
	tag := "@" + mention
	return fmt.Sprintf("## CodeReview\n\nInclude a question after the command, for example `%s ask why is this mutex held across the HTTP call?`\n\n<sub>Generated by CodeReview.</sub>\n%s", tag, askMarker)
}
