package review

import (
	"strings"
	"testing"

	"github.com/nicolaeser/codereview/internal/gitlab"
)

func TestNoteMentionsBot(t *testing.T) {
	aliases := []string{"codereview", "cr"}
	if !NoteMentionsBot("@codereview skip", aliases) {
		t.Fatal("expected mention of @codereview")
	}
	if !NoteMentionsBot("hey @CR please", aliases) {
		t.Fatal("expected alias match to be case-insensitive")
	}
	if NoteMentionsBot("please skip this", aliases) {
		t.Fatal("plain skip without mention must not match")
	}
}

func TestParseThreadCommand(t *testing.T) {
	aliases := []string{"codereview", "cr"}
	tests := []struct {
		body string
		want ThreadCommand
	}{
		{"@codereview that's a false positive, skip", CommandSkip},
		{"@codereview skip", CommandSkip},
		{"@codereview ignore", CommandSkip},
		{"@codereview false-positive", CommandSkip},
		{"@codereview please review", CommandReview},
		{"@codereview re-review this", CommandReview},
		{"@codereview full review", CommandFullReview},
		{"@codereview full-review", CommandFullReview},
		{"@codereview fullreview", CommandFullReview},
		{"@codereview full_review", CommandFullReview},
		{"@codereviewfullreview", CommandFullReview},
		{"@codereview resolve", CommandResolve},
		{"@codereview help", CommandHelp},
		{"@codereview ask why is this racy", CommandAsk},
		{"@codereview prompt explain the mutex", CommandAsk},
		{"@codereview question why atoi", CommandAsk},
		{"@codereviewprompt why atoi", CommandAsk},
		{"that's a false positive, skip", CommandNone},
		{"skip", CommandNone},
		{"@codereview", CommandHelp},
		{"@codereview thanks", CommandHelp},
		{"", CommandNone},
		{HelpMarkdown("codereview"), CommandNone},
	}
	for _, test := range tests {
		if got := ParseThreadCommand(test.body, aliases); got != test.want {
			t.Errorf("ParseThreadCommand(%q) = %s, want %s", test.body, got, test.want)
		}
	}
}

func TestHumanThreadCommandSkipAfterFindingNote(t *testing.T) {
	finding := Finding{Path: "main.go", Line: 3, Title: "Empty helper"}
	aliases := []string{"codereview"}
	skip := gitlab.Discussion{Notes: []gitlab.Note{
		{Body: "prior\n" + findingMarkerComment(FindingID(finding)), Author: gitlab.User{Username: "codereview"}},
		{Body: "@codereview that's a false positive, skip", Author: gitlab.User{Username: "dev"}},
	}}
	if got := humanThreadCommand(skip, aliases); got != CommandSkip {
		t.Fatalf("human skip = %s, want skip", got)
	}

	noMention := skip
	noMention.Notes[1].Body = "that's a false positive, skip"
	if got := humanThreadCommand(noMention, aliases); got != CommandNone {
		t.Fatalf("skip without mention = %s, want none", got)
	}

	bot := skip
	bot.Notes[1].Author = gitlab.User{Username: "project_1_bot_hash"}
	if got := humanThreadCommand(bot, aliases); got != CommandNone {
		t.Fatalf("automation skip = %s, want none", got)
	}

	inFinding := gitlab.Discussion{Notes: []gitlab.Note{
		{Body: "@codereview skip\n" + findingMarkerComment(FindingID(finding)), Author: gitlab.User{Username: "dev"}},
	}}
	if got := humanThreadCommand(inFinding, aliases); got != CommandNone {
		t.Fatalf("skip in finding note = %s, want none", got)
	}

	review := gitlab.Discussion{Notes: []gitlab.Note{
		{Body: findingMarkerComment(FindingID(finding)), Author: gitlab.User{Username: "codereview"}},
		{Body: "@codereview please review", Author: gitlab.User{Username: "dev"}},
	}}
	if got := humanThreadCommand(review, aliases); got != CommandReview {
		t.Fatalf("human review = %s, want review", got)
	}

	help := gitlab.Discussion{Notes: []gitlab.Note{
		{Body: findingMarkerComment(FindingID(finding)), Author: gitlab.User{Username: "codereview"}},
		{Body: "@codereview", Author: gitlab.User{Username: "dev"}},
	}}
	if got := humanThreadCommand(help, aliases); got != CommandHelp {
		t.Fatalf("bare mention = %s, want help", got)
	}
}

func TestSkipReplyBodyIsSticky(t *testing.T) {
	body := SkipReplyBody()
	if !strings.Contains(body, skipMarker) {
		t.Fatalf("skip reply missing marker: %s", body)
	}
	if !ownedSkipNote(body) {
		t.Fatal("skip reply must be recognized as an owned skip")
	}
}

func TestHelpMarkdownListsCommands(t *testing.T) {
	body := HelpMarkdown("codereview")
	for _, want := range []string{
		"## CodeReview commands",
		"`@codereview skip`",
		"`@codereview review`",
		"`@codereview review <focus>`",
		"`@codereview full-review`",
		"`@codereview ask <question>`",
		"`@codereview prompt`",
		"`@codereview resolve`",
		"`@codereview help`",
		"`@codereview ignore`",
		"skip-codereview",
		"[skip review]",
		"silent by default",
		"Generated by CodeReview",
		helpMarker,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("help missing %q:\n%s", want, body)
		}
	}
	if ParseThreadCommand(body, []string{"codereview"}) != CommandNone {
		t.Fatal("posted help must not parse as skip or review")
	}
}

func TestParseMentionRequestExtraFocus(t *testing.T) {
	aliases := []string{"codereview"}
	got := ParseMentionRequest("@codereview review also check race conditions in worker.go", aliases)
	if got.Command != CommandReview || got.Extra != "also check race conditions in worker.go" {
		t.Fatalf("review extra = %#v", got)
	}
	for _, body := range []string{
		"@codereview full review look at SQL injection",
		"@codereview full-review look at SQL injection",
		"@codereview fullreview look at SQL injection",
	} {
		full := ParseMentionRequest(body, aliases)
		if full.Command != CommandFullReview || full.Extra != "look at SQL injection" {
			t.Fatalf("full extra for %q = %#v", body, full)
		}
	}
	ask := ParseMentionRequest("@codereview ask is this mutex held across the HTTP call?", aliases)
	if ask.Command != CommandAsk || !strings.Contains(ask.Extra, "mutex held") {
		t.Fatalf("ask extra = %#v", ask)
	}
	skip := ParseMentionRequest("@codereview skip because tests cover it", aliases)
	if skip.Command != CommandSkip || skip.Extra != "" {
		t.Fatalf("skip must not keep leftover: %#v", skip)
	}
	secret := ParseMentionRequest("@codereview review token AKIA0000000000FAKE00", aliases)
	if secret.Command != CommandReview || strings.Contains(secret.Extra, "AKIA0000000000FAKE00") {
		t.Fatalf("extra must be redacted: %#v", secret)
	}
	if ParseMentionRequest(FormatAskReply("hello"), aliases).Command != CommandNone {
		t.Fatal("posted ask reply must not parse as a command")
	}
}

func TestMRDisableTokenFromTitleAndLabel(t *testing.T) {
	tokens := []string{"skip-codereview", "[skip review]", "no-codereview"}
	if _, ok := mrDisableToken(gitlab.MergeRequest{Title: "Fix login"}, tokens); ok {
		t.Fatal("plain title must not disable")
	}
	if token, ok := mrDisableToken(gitlab.MergeRequest{Title: "WIP skip-codereview: experiments"}, tokens); !ok || token != "skip-codereview" {
		t.Fatalf("title token = %q ok=%t", token, ok)
	}
	if token, ok := mrDisableToken(gitlab.MergeRequest{Title: "Add API", Labels: []string{"backend", "no-codereview"}}, tokens); !ok || token != "no-codereview" {
		t.Fatalf("label token = %q ok=%t", token, ok)
	}
	if token, ok := mrDisableToken(gitlab.MergeRequest{Title: "chore: [skip review] docs"}, tokens); !ok {
		t.Fatalf("bracket token missing, got %q", token)
	}
}
